[project]
name = "vorstellungsgesprach"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "elianezanlorense", email = "58109901+elianezanlorense@users.noreply.github.com" }
]
requires-python = ">=3.12"
dependencies = []

[project.scripts]
vorstellungsgesprach = "vorstellungsgesprach:main"

[build-system]
requires = ["uv_build>=0.12.4,<0.13.0"]
build-backend = "uv_build"
