"""
Simple feedback logging module.

Stores each user interaction (question, retrieved concept, generated answer,
rating, and free-text comment) in a local SQLite database for later manual
review and dataset/prompt improvement.
"""

import sqlite3
from datetime import datetime, timezone
from pathlib import Path

DB_PATH = Path("data/feedback.db")


def _get_connection() -> sqlite3.Connection:
    DB_PATH.parent.mkdir(parents=True, exist_ok=True)
    return sqlite3.connect(DB_PATH)


def init_feedback_db() -> None:
    """Create the feedback table if it doesn't exist yet. Call once at startup."""
    with _get_connection() as conn:
        conn.execute(
            """
            CREATE TABLE IF NOT EXISTS feedback (
                id INTEGER PRIMARY KEY AUTOINCREMENT,
                created_at TEXT NOT NULL,
                question TEXT NOT NULL,
                concept_id TEXT,
                answer TEXT NOT NULL,
                rating INTEGER,
                comment TEXT
            )
            """
        )


def save_feedback(
    question: str,
    answer: str,
    concept_id: str | None = None,
    rating: int | None = None,
    comment: str | None = None,
) -> None:
    """Persist one feedback entry.

    Args:
        question: The user's original question.
        answer: The answer generated by the RAG pipeline.
        concept_id: ID of the retrieved concept, if available.
        rating: Optional numeric rating (e.g. 1 for 👍, -1 for 👎).
        comment: Optional free-text comment from the user.
    """
    with _get_connection() as conn:
        conn.execute(
            """
            INSERT INTO feedback (created_at, question, concept_id, answer, rating, comment)
            VALUES (?, ?, ?, ?, ?, ?)
            """,
            (
                datetime.now(timezone.utc).isoformat(),
                question,
                concept_id,
                answer,
                rating,
                comment,
            ),
        )


def load_all_feedback() -> list[dict]:
    """Return all stored feedback rows as a list of dicts, for review/export."""
    with _get_connection() as conn:
        conn.row_factory = sqlite3.Row
        rows = conn.execute("SELECT * FROM feedback ORDER BY created_at DESC").fetchall()
        return [dict(row) for row in rows]