ANSWER_PROMPT = """
Du hilfst einer Person dabei, technisches Deutsch zu lernen.

Basierend auf dem folgenden Konzept, beantworte die Nutzerfrage NICHT mit
einem langen Fließtext. Gib stattdessen zurück:
1. Eine sehr kurze Einleitung (maximal ein Satz)
2. Die wichtigsten Ausdrücke aus dem Konzept, die man sich merken sollte

Nutzerfrage: {query}

Konzept:
Thema: {topic}
Frage: {question_de}
Antwort: {answer_de}
Wichtige Ausdrücke: {phrases}

Antworte ausschließlich mit einem gültigen JSON-Objekt:
{{"intro": "...", "phrases": ["...", "...", "..."]}}
""".strip()



JUDGE_PROMPT = """
You are evaluating an answer generated by a German technical-learning
assistant.

Evaluate the generated answer against the reference concept.
Evaluation criteria:
- faithfulness: The answer is supported by the reference.
- relevance: The answer addresses the user query.
- language_quality: The German is clear and grammatically appropriate.
- phrase_quality: The selected phrases are useful and related to the concept.
- overall: Overall answer quality.

Use integer scores from 1 to 5:

1 = very poor
2 = poor
3 = acceptable
4 = good
5 = excellent

User query:{query}
Expected concept ID:{expected_id}
Retrieved concept ID:{retrieved_id}
Reference topic:{topic}
Reference answer:{reference_answer}
Reference phrases:{reference_phrases}
Generated answer:{generated_answer}
Return only valid JSON:

{{
  "faithfulness": 1,
  "relevance": 1,
  "language_quality": 1,
  "phrase_quality": 1,
  "overall": 1,
  "reason": "Short explanation."
}}
""".strip()
